services:
  egovim:
    container_name: egovim
    build: .
    volumes:
      - ./config/nvim:/home/developer/.config/nvim
      - ../:/home/developer/projects
    image: egovim:latest
    user: developer
    tty: true
    stdin_open: true